### PR TITLE
DigiAssets Support and iOS 14 optimizations

### PR DESCRIPTION
**Pull request by SmartArray**
This PR contains hundreds of improvements and a dozens of features. To name a few:

- DigiAsset Support
- iOS 14 Support
- Stricter Digi-ID Implementation
- AddressBook
- Dandelion Support
- Today Extension

### CODE REVIEW

**Review by gto90 — APPROVED** [review]
utACK

**Comment by gto90** [comment]
@SmartArray ,

I reviewed this and it looks good but there are quite a few merge conflicts that need to be resolved.  Thanks for all the hard work on this!

**Comment by SmartArray** [comment]
> @SmartArray ,
> 
> I reviewed this and it looks good but there are quite a few merge conflicts that need to be resolved. Thanks for all the hard work on this!

Thanks for reviewing! Should be good now.

**Comment by SmartArray** [comment]
ACK from myself. I compiled and tested the project once more, to be sure I did not break anything.

**Pull request merged**
